service:
  type: NodePort
  nodePort: 30001

labels:
  app.kubernetes.io/name: kibana

secretMounts:
 - name: kibana-config
   secretName: kibana-config
   path: /tmp/kibana-config
lifecycle:
  postStart:
    exec:
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' http://localhost:5601/app/kibana)" != "200" ]]; do sleep 1; done
          curl -XPOST 'http://localhost:5601/api/saved_objects/_import' -H "kbn-xsrf: true" --form file=@/tmp/kibana-config/kibana.config.ndjson
