---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scope-k8s-demo-telegraf-conf
data:
  telegraf.conf: |
    [global_tags]

    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false

    [[outputs.prometheus_client]]
      listen = ":9273"

    [[processors.override]]
      [processors.override.tags]
        metric_type = "gauge"

    [[inputs.statsd]]
      protocol = "tcp"
      service_address = ":8125"
      datadog_extensions = true
      delete_counters = true
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
    spec:
      containers:
        - image: cribl/scope-k8s-demo-telegraf
          imagePullPolicy: IfNotPresent
          name: telegraf
          env:
          - name: "SCOPE_EVENT_HTTP_HEADER"
            value: "(?i)Cookie.*"
          ports:
            - containerPort: 8125
            - containerPort: 9273
          resources: 
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: telegraf-etc
              mountPath: /etc/telegraf
      volumes:
        - name: telegraf-etc
          configMap:
            name: scope-k8s-demo-telegraf-conf
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: telegraf
  name: telegraf
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "8125"
      port: 8125
      targetPort: 8125
    - name: "9273"
      port: 9273
      targetPort: 9273
  selector:
    app.kubernetes.io/name: telegraf
